return {}
-- return {
-- 	"huggingface/llm.nvim",
-- 	opts = {
-- 		backend = "ollama",
-- 		url = "http://localhost:11434",
--
-- 		model = "starcoder",
-- 		tokens_to_clear = { "<|endoftext|>" },
-- 		fim = {
-- 			enabled = true,
-- 			prefix = "<fim_prefix>",
-- 			middle = "<fim_middle>",
-- 			suffix = "<fim_suffix>",
-- 		},
-- 		context_window = 8192,
-- 		tokenizer = {
-- 			repository = "bigcode/starcoder",
-- 		},
-- 	},
-- }
